TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB 		    += devoxford.db
DB_INSTALLS += $(TOP)/oxfordSup/devoxford.proto

#=======================================
include $(TOP)/configure/RULES
